const Services = {
  website: [
    {
      id: 1,
      title: "Chhavi Paliwal",
      description:
        "Discover the portfolio of Chhavi Paliwal, a highly skilled web developer well-versed in ReactJS and NodeJS. With a passion for freelancing, I create dynamic and user-friendly web solutions tailored to your needs.",
      logo: "favicon.ico",
      keywords: "chhavi paliwal",
      specilize: "Web Developer",
      link: "https://react-portfolio-kitti.netlify.app/",
      contact: "+91 8193907462",
      email: "chhavipaliwal1203@gmail.com",
      address: "Agra, Uttar Pradesh",
    },
  ],

  aboutMe: [
    {
      id: 1,
      name: "Chhavi Paliwal",
      nickName: "Kitti",
      codeName: "kittify",
      image: "/kitti.jpeg",
      tagline: "Crafting digital delights with Web and AI 👋",
      quote:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      description:
        "Technology and AI have the power to change our world, but it's up to us to ensure it's for the betterment of humanity.",
      specilize: "Web Developer",
      professions: [
        "Developer",
        "Designer",
        "Programmer",
        "Freelancer",
        "Machine Learner",
        "Web Developer",
      ],
      location: "Agra, Uttar Pradesh",
      email: "chhavipaliwal1203@gmail.com",
      phone: "+91 8193907462",
    },
  ],
  services: [
    {
      id: 1,
      title: "Web Developement",
      image: "fa-regular fa-window",
      description: "Knowledge of 8+ programming languages",
      color: "#fc9401",
      background: "#fc93014d",
    },
    {
      id: 2,
      title: "UI Design",
      image: "fa-regular fa-sidebar",
      description: "Proficient in creating user-friendly interfaces.",
      color: "#e7385d",
      background: "#e7385e3e",
    },
    {
      id: 3,
      title: "Photo/Video Editing",
      image: "fa-regular fa-camera",
      description: "Proficient in editing visual content.",
      color: "#604868",
      background: "#60486841",
    },
    {
      id: 4,
      title: "App Design",
      image: "fa-regular fa-compass-drafting",
      description: "Knowledge of more than 5 programming languages",
      color: "#fc9401",
      background: "#431922",
    },
  ],
  technologies: [
    {
      id: 1,
      image: "/kitti.jpeg",
      title: "Web Development",
      techs: [
        {
          id: 1,
          name: "HTML",
        },
        {
          id: 2,
          name: "CSS",
        },
        {
          id: 3,
          name: "JavaScript",
        },
      ],
    },
    {
      id: 2,
      image: "/kitti.jpeg",
      title: "UX/UI Design",
      techs: [
        {
          id: 1,
          name: "Figma",
        },
        {
          id: 2,
          name: "Adobe XD",
        },
        {
          id: 3,
          name: "Adobe Illustrator",
        },
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Invoice Generator",
      description:
        "Invoice Generator is a streamlined web application that simplifies invoice creation with customizable templates, allowing users to generate, edit, and export professional invoices efficiently. This project showcases my ability to develop practical business solutions using modern web technologies.",
      technologies: "NEXT JS, Tailwind CSS, Hero UI",
      link: "https://github.com/chhavipaliwal/invoice-generator",
      previewLink: "https://chhavi-paliwal-invoice-generator.vercel.app/",
      startDate: "2025-02-16",
      endDate: "2025-02-25",
      priority: 1,
      images: ["invoice-generator-1.png", "invoice-generator-2.png"],
    },
    {
      id: 6,
      title: "The Yogic Bowl",
      description:
        "A website for cafe in Rishikesh, Uttarakhand. Made with Next JS, Tailwind CSS, and HeroUI, this project showcases my skills in front-end development and design.",
      technologies: "Next JS, Tailwind CSS, HeroUI",
      link: "https://github.com/chhavipaliwal/the-yogic-bowl",
      previewLink: "https://the-yogic-bowl.vercel.app/",
      startDate: "2024-12-01",
      endDate: "2024-12-10",
      priority: 1,
      images: ["theyogicbowl-1.png", "theyogicbowl-2.png"],
    },
    {
      id: 2,
      title: "The Kody",
      description:
        "A simple and elegant template for a personal blog. Made with React, Tailwind CSS, and Formik, this project showcases my skills in front-end development and design.",
      technologies: "React, Tailwind, Formik",
      link: "https://github.com/chhavipaliwal/thekody",
      previewLink: "https://the-kody.netlify.app",
      startDate: "2024-11-04",
      endDate: "2024-11-18",
      priority: 1,
      images: ["the-kody.png"],
    },
    {
      id: 3,
      title: "Modern Blog Interface",
      description:
        "Our blog combines HTML, CSS, and JavaScript for a sleek and interactive design. HTML structures the content, CSS enhances visuals, and JavaScript adds interactivity, ensuring an engaging and enjoyable reading experience.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/chhavipaliwal/blog",
      previewLink: "https://blog-template-kitti.netlify.app",
      startDate: "2022-11-04",
      endDate: "2022-11-18",
      priority: 1,
      images: ["blog-homepage.png", "blog-page.png"],
    },
    {
      id: 5,
      title: "Analog Clock",
      description:
        "The Analog Clock project is a captivating web application designed to bring classic timekeeping to the digital age. Crafted with HTML, CSS, and JavaScript, this interactive clock offers a timeless experience with a modern twist.",
      technologies: "HTML, CSS, JS",
      link: "https://github.com/chhavipaliwal/analog-clock",
      previewLink: "https://analog-clock-kitti.netlify.app",
      startDate: "2022-09-01",
      endDate: "2022-09-01",
      priority: 3,
      images: ["analog-clock.png"],
    },

    {
      id: 9,
      title: "Credit Card Mockup",
      description:
        "The Credit Card Mockup is a succinct and informative one-page website designed to empower individuals with essential knowledge about credit cards. Developed as a static, single-page resource, this platform serves as a valuable guide for anyone seeking to demystify the world of credit and financial management.",
      technologies: "HTML, CSS",
      link: "https://github.com/chhavipaliwal/credit-card",
      previewLink: "https://credit-card-chhavipaliwal.vercel.app",
      startDate: "2022-12-01",
      endDate: "2022-12-04",
      priority: 3,
      images: ["credit-card.png"],
    },
    {
      id: 10,
      title: "Portfolio Website",
      description:
        "The Portfolio Website is a static web application that showcases my skills, projects, and experience. Crafted with HTML, CSS, and JavaScript, this website offers a comprehensive overview of my professional journey, providing a glimpse into my skills and expertise.",
      technologies: "HTML, CSS, ReactJs",
      link: "",
      previewLink: "https://portfolio-chhavipaliwal.vercel.app",
      startDate: "2023-08-01",
      endDate: "2023-10-01",
      priority: 2,
      images: ["portfolio.png"],
    },
  ],
  skills: [
    {
      id: 1,
      title: "NextJs",
      percentage: 80,
      image: "devicon:nextjs",
      description:
        "Skilled in Next Js, I create dynamic and interactive web content.",
      color: "#000",
      background: "#00000020",
      isFontAwesome: true,
    },
    {
      id: 2,
      title: "ReactJs",
      percentage: 90,
      image: "devicon:react",
      description:
        "I create visually appealing and responsive web designs through CSS mastery.",
      color: "#58C4DC",
      background: "#58C4DC20",
      isFontAwesome: true,
    },
    {
      id: 3,
      title: "Tailwind CSS",
      percentage: 90,
      image: "devicon:tailwindcss",
      description:
        "I create dynamic and interactive web content using Tailwind CSS.",
      color: "#38BDF9",
      background: "#38BDF920",
      isFontAwesome: true,
    },
    {
      id: 4,
      title: "NodeJs",
      percentage: 80,
      image: "devicon:nodejs",
      description:
        "Proficient in NodeJs, I have a strong foundation in programming, enabling me to tackle a wide range of tasks and solve problems efficiently.",
      color: "#5BAC47",
      background: "#5BAC4720",
      isFontAwesome: true,
    },
    {
      id: 5,
      title: "React",
      percentage: 65,
      image: "fa-brands fa-react",
      description:
        "I specialize in React.js, a powerful library for building dynamic and interactive user interfaces. With expertise in component-driven development, I create responsive and engaging web applications that provide a seamless user experience.",
      color: "#5ed4f3",
      background: "#4381b028",
      isFontAwesome: true,
    },
    {
      id: 6,
      title: "Node",
      percentage: 50,
      image: "fa-brands fa-node-js",
      description:
        "I'm in the process of mastering Node.js, a server-side JavaScript runtime, to build scalable and efficient web applications.",
      color: "#509941",
      background: "#50994140",
      isFontAwesome: true,
    },
    {
      id: 7,
      title: "PHP",
      percentage: 70,
      image: "fa-brands fa-php",
      description:
        "Proficient in PHP, I create dynamic web applications and websites with server-side scripting, adding functionality and interactivity to enhance user experiences.",
      color: "#8993be",
      background: "#8993be40",
      isFontAwesome: true,
    },
    {
      id: 8,
      title: "SQL",
      percentage: 70,
      image: "fa-solid fa-database",
      description:
        "I possess a foundational understanding of SQL, allowing me to query databases and manage data effectively, while continuously expanding my skills in database management.",
      color: "#f29111",
      background: "#f291112a",
      isFontAwesome: true,
    },
    {
      id: 9,
      title: "MongoDB",
      percentage: 60,
      image: "fa-brands fa-envira",
      description:
        "Currently exploring MongoDB to gain proficiency in NoSQL database management and enhance my data storage and retrieval skills.",
      color: "#4db33d",
      background: "#4db33d2a",
      isFontAwesome: true,
    },
    {
      id: 10,
      title: "Git",
      percentage: 70,
      image: "fa-brands fa-git-alt",
      description:
        "I am in the early stages of learning Git, a version control system, to manage and collaborate on software development projects.",
      color: "#f05639",
      background: "#f056393d",
      isFontAwesome: true,
    },
    {
      id: 11,
      title: "C++",
      percentage: 50,
      image: "cpp.png",
      description:
        "I am in the early stages of learning C++, a general-purpose programming language, to manage and collaborate on software development projects.",
      color: "#6c7b8b",
      background: "#6c7b8b2a",
      isFontAwesome: false,
    },
    {
      id: 12,
      title: "BootStrap",
      percentage: 80,
      image: "fa-brands fa-bootstrap",
      description:
        "I have a deep understanding of Bootstrap, leveraging its responsive design and UI components to create aesthetically pleasing and user-friendly web interfaces.",
      color: "#563d7c",
      background: "#563d7c2a",
      isFontAwesome: true,
    },
    {
      id: 13,
      title: "Canva",
      percentage: 90,
      image: "canva.png",
      description:
        "I have a deep understanding of Canva, leveraging its responsive design and UI components to create aesthetically pleasing and user-friendly web interfaces.",
      color: "#12a9d2",
      background: "#12a9d22b",
      isFontAwesome: false,
    },
  ],
  education: [
    {
      id: 1,
      title: "Bachelor of computer science and technology",
      institutionShort: "LPU",
      institutionLong: "Lovely Professional University",
      location: "Phagwara, Punjab",
      year: "2026",
      link: "https://www.lpu.in",
    },
    {
      id: 2,
      title: "XIIth from CBSE",
      institutionShort: "St. Andrews School",
      institutionLong: "St. Andrews School",
      location: "Agra, Uttar Pradesh",
      year: "2021",
      link: "https://schools.org.in/jhajjar/06150401002/adarsh-sr-sec-school-dadanpur.html",
    },
    {
      id: 3,
      title: "Xth from CBSE",
      institutionShort: "St. Andrews School",
      institutionLong: "St. Andrews School",
      location: "Agra, Uttar Pradesh",
      year: "2019",
      link: "https://schools.org.in/jhajjar/06150401002/adarsh-sr-sec-school-dadanpur.html",
    },
  ],
  certificates: [
    {
      id: 1,
      priority: 3,
      title: "Introduction to HTML, CSS and Javascript",
      image: "1.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://coursera.org/share/d62c0e3891b61b3bb5bea3981df8fc81",
    },
    {
      id: 2,
      priority: 3,
      title: "Introduction to Cloud Computing",
      image: "2.png",
      institution: "IBM",
      location: "Online",
      year: "2022",
      duration: "12hrs",
      link: "https://www.coursera.org/account/accomplishments/verify/6YAE6J7KE92H",
    },
    {
      id: 3,
      priority: 3,
      title: "Getting Started with AI and Machine Learning",
      image: "3.png",
      institution: "LinkedIn",
      location: "Online",
      year: "2023",
      duration: "9hrs",
      link: "https://www.linkedin.com/learning/certificates/8aa845d977a5904fe0903b4c4848c68bc78927251ed5e90df2dc1094c30c6fa6",
    },
    {
      id: 4,
      priority: 3,
      title: "Computer Architecture and Organization",
      image: "4.png",
      institution: "Udemy",
      location: "Online",
      year: "2023",
      duration: "12hrs",
      link: "https://www.udemy.com/certificate/UC-fb8a6728-5817-493b-a993-adede0a5fdd6/",
    },
    {
      id: 5,
      priority: 3,
      title: "Fundamentals of Management",
      image: "5.png",
      institution: "UCI",
      location: "Online",
      year: "2023",
      duration: "6hrs",
      link: "https://coursera.org/share/d175e0b3fce0742c82cb385b724dc7df",
    },
  ],
  links: [
    {
      id: 1,
      title: "X",
      link: "https://twitter.com/chhavipaliwal",
      icon: "fa-brands fa-twitter",
      color: "#22a0f0",
      featured: 1,
    },
    {
      id: 2,
      title: "LinkedIn",
      link: "https://linkedin.com/in/chhavipaliwal",
      icon: "fa-brands fa-linkedin",
      color: "#0077b5",
      featured: 1,
    },
    {
      id: 3,
      title: "Github",
      link: "https://telegram.me/chhavipaliwal",
      icon: "fa-brands fa-github",
      color: "#0088cc",
      featured: 0,
    },
    {
      id: 4,
      title: "Instagram",
      link: "https://www.instagram.com/chhavipaliwal",
      icon: "fa-brands fa-instagram",
      color: "#e1306c",
      featured: 1,
    },
    {
      id: 5,
      title: "Github",
      link: "https://github.com/chhavipaliwal",
      icon: "fa-brands fa-github",
      color: "#333333",
      featured: 1,
    },

    {
      id: 17,
      title: "Dribbble",
      link: "https://dribbble.com/chhavipaliwal",
      icon: "fa-brands fa-dribbble",
      color: "#ea4c89",
      featured: 0,
    },
    {
      id: 20,
      title: "Behance",
      link: "https://www.behance.net/chhavipaliwal",
      icon: "fa-brands fa-behance",
      color: "#1769ff",
      featured: 0,
    },
    {
      id: 23,
      title: "HackerRank",
      link: "https://www.hackerrank.com/chhavipaliwal",
      icon: "fa-brands fa-hackerrank",
      color: "#2ec866",
      featured: 0,
    },
  ],
};

export default Services;
